acoes/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path
from .views import create_acoe, delete_acoe, list_acoes, update_acoe, find_or_create_acao

#  Rotas, para a APP de acao

urlpatterns = [

    path('lista', list_acoes, name='list_acoes'),
    path('novo', create_acoe, name='create_acao'),
    path('update/<int:id>/', update_acoe, name='update_acao'),
    path('deletar/<int:id>/', delete_acoe, name='delete_acao'),
    
    
]

cd_acoes/urls.py
from re import template
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include
from . import view
from .views.relatorio_acao import relatorio_especifico, relatorio_geral

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view.dashboard, name='dashboard'),
    path('dashboard', TemplateView.as_view(template_name="dashboard.html")),
    
#ana
    path('login', TemplateView.as_view(template_name="layout/formularios/login.html")),
    path('esqueceu_senha', TemplateView.as_view(template_name="layout/formularios/esqueceu_senha.html")),
    path('tela_inicial', TemplateView.as_view(template_name="layout/telas_Iniciais/tela_inicial.html")),
    path('listar_acoes', TemplateView.as_view(template_name="layout/acoes/acoes.html")),
    path('criar_carteira', TemplateView.as_view(template_name="layout/carteiras/criar_carteira.html")),
    path('infos_acoes', TemplateView.as_view(template_name="layout/acoes/informacoes_sobre_as_acoes.html")),
  

#samara
    path('telainicial2', TemplateView.as_view(template_name="layout/telas_iniciais/telainicial2.html")),
    path('edicaodacarteira', TemplateView.as_view(template_name="layout/carteiras/edicaodacarteira.html")),
    path('relatorios', TemplateView.as_view(template_name="layout/relatorios/relatorios.html")),
    path('relatoriosespecificos', TemplateView.as_view(template_name="layout/relatorios/relatoriosespecificos.html")),
   # path('cadastro', TemplateView.as_view(template_name="layout/formularios/cadastro.html")),
    path('configuracoesdeusuario', TemplateView.as_view(template_name="layout/config.usuarios/configuracoesdeusuario.html")),

   
   
#icaro
    path('', include('usuarios.urls')),
    path('acoes/', include('acoes.urls')),
    path('carteiras/', include('carteiras.urls')),
    #path('login/', include('usuarios.urls')),
    path('relatorio_geral', relatorio_geral.relatorio_geral, name='relatorio_geral'),
    path('relatorio_especifico_carteira', relatorio_especifico.relatorio_especifico, name='relatorio_especifico_carteira'),



#king

   


 

]

usuarios/urls.py
from django.urls import path

app_name = 'accounts'

from . import views

urlpatterns = [
    path('cadastrar', views.home, name='cadastrar_usuario'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout')
]

templates/layout/layout.html
{%load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href={% static "vendor/fontawesome-free/css/all.min.css" %} rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link rel="shortcut icon" href={% static "img/carteira_cripto1.png" %} type="image/x-icon">

    <!-- Custom styles for this template-->
    <link href={% static "css/sb-admin-2.min.css" %} rel="stylesheet">
    {% block css%}{% endblock %}

</head>

<body id="page-top">
    {% if user.is_authenticated %}
      
      
       
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav text-dark sidebar accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href={% url "dashboard"%}>
                <div class="sidebar-brand-icon rotate-n-15">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-wallet2" viewBox="0 0 16 16">
                        <path d="M12.136.326A1.5 1.5 0 0 1 14 1.78V3h.5A1.5 1.5 0 0 1 16 4.5v9a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 13.5v-9a1.5 1.5 0 0 1 1.432-1.499L12.136.326zM5.562 3H13V1.78a.5.5 0 0 0-.621-.484L5.562 3zM1.5 4a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-13z"/>
                      </svg>
                </div>
                <div class="sidebar-brand-text text-dark mx-3">CD-Ações</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link text-dark" href={% url "dashboard"%}>
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
                    
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Carteira
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'list_carteiras'%}" >
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Minhas carteiras</span>
                </a>
                
            </li>
            
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Relatórios
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                    aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Relatórios</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="{% url 'relatorio_geral'%}">Relatório Geral</a>
                        <a class="collapse-item" href="{% url 'relatorio_especifico_carteira'%}">Relatório Ação Específico</a>                        
                    </div>
                </div>
            </li>


 <!-- Divider -->
 <hr class="sidebar-divider">

 <!-- Heading -->
 <div class="sidebar-heading">
     AÇÕES
 </div>

 <!-- Nav Item - Pages Collapse Menu -->
 <li class="nav-item">
     <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseone"
         aria-expanded="true" aria-controls="collapsePages">
         <i class="fas fa-fw fa-folder"></i>
         <span>Minhas ações</span>
     </a>
     <div id="collapseone" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
         <div class="bg-white py-2 collapse-inner rounded">
           
             <a class="collapse-item" href="{%url 'list_acoes'%}">Informaçẽos Sobre Ações</a>
            
       
             
         </div>
     </div>
 </li>













            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <!-- <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src={% static "img/undraw_rocket.svg" %} alt="...">
                <p class="text-center mb-2"><strong>CD-Ações</strong> é embalado com recursos premium, componentes e muito mais!</p>
                <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Seja Um Premiun!</a>
            </div> -->

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">

                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>

                                    </div>
                                </form>
                            </div>
                        </li>

                      

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">  <p class="mr-2" style="color: #0000ff;margin-bottom: -6px;text-decoration: underline;">{{ user.get_full_name|default:user.username }}
                                    logado
                
                                </p></span>
                              


                                <img class="img-profile rounded-circle"
                                    src={% static "img/undraw_profile.svg" %}>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                
                              <div class="dropdown-divider"></div>

                             <!--   <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal"-->
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                <a href="{% url 'accounts:user_logout' %}"> Sair
                                </a>
                                    
                                    
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                
                {% block content %}
                
                {% endblock %}

                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; <a href="https://github.com/Web-2-Carteira-de-Acoes">IFBaiano</a> 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Deseja sair?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src={% static "vendor/jquery/jquery.min.js" %}></script>
    <script src={% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>

    <!-- Core plugin JavaScript-->
    <script src={% static "vendor/jquery-easing/jquery.easing.min.js" %}></script>

    <!-- Icons do Fontawesome -->
    <script src="https://kit.fontawesome.com/893b300611.js" crossorigin="anonymous"></script>
    
    <!-- Custom scripts for all pages-->
    <script src={% static "js/sb-admin-2.min.js" %}></script>

    <!-- Page level plugins -->
    <script src={% static "vendor/chart.js/Chart.min.js" %}></script>

    <!-- Page level custom scripts -->
    <script src={% static "js/demo/chart-area-demo.js" %}></script>
    <script src={% static "js/demo/chart-pie-demo.js" %}></script>
    {% else %}

   <div class="container py-5 h-100">
        <div class="d-flex justify-content-center align-items-center h-150">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card cardlogin text-black" style="border-radius: 4rem; background-image: linear-gradient(0.59deg, #64C9FF 0.51%, rgba(71, 236, 255, 0.21) 97.67%);;">
                    <div class="card-body p-3 ps-3 pe-3 text-center" style="height: 300px; ">
    
                        <div class="mt-md-4">
                            <p class="mt-3" style="background: white; color: blue; font-size: 22px; border-radius:18px;">  Você não possui acesso ao sistema, por favor efetuar o login para acessar </p>
                                <a href="{% url 'accounts:user_login' %}"><p class="mb-4" style="background: #0033ff;color: white; width: 140px; margin-left:130px;border-radius: 13px;font-size: 21px;  margin-bottom: 70px; ">Fazer Login<p></a>
                                <a href="{% url 'accounts:cadastrar_usuario' %}"><pclass="mb-2" style="background: #0033ff;color: white; width: 181px; border-radius: 13px; font-size: 21px;">Cadastrar<p></a>
                           

    
                        </div>
    
                        <div>
                           
                        </div>
    
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</body>

</html>